apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ci-cd-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-ci-cd-demo
  template:
    metadata:
      labels:
        app: k8s-ci-cd-demo
    spec:
    containers:
      - name: k8s-ci-cd-demo
        image: halsstech/k8s-ci-cd-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ci-cd-demo
spec:
  type: NodePort
  selector:
    app: k8s-ci-cd-demo
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
