name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # ✅ Use your local runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/k8s-ci-cd-demo
          docker build -t $IMAGE_NAME:${GITHUB_SHA} .
          docker push $IMAGE_NAME:${GITHUB_SHA}

      - name: Set KUBECONFIG
        run: |
          echo "KUBECONFIG=$env:USERPROFILE\.kube\config" >> $env:GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          kubectl config use-context minikube
          kubectl set image deployment/k8s-ci-cd-demo k8s-ci-cd-demo=${{ secrets.DOCKER_USERNAME }}/k8s-ci-cd-demo:${GITHUB_SHA}
          kubectl rollout status deployment/k8s-ci-cd-demo
